/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mikeneck.graalvm;

import org.gradle.api.Task;
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;

import static org.hamcrest.CoreMatchers.instanceOf;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'org.mikeneck.graalvm.greeting' plugin.
 */
public class GraalvmNativeImagePluginTest {

    @Test public void pluginRegistersExtension() {
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("java");

        project.getPlugins().apply("org.mikeneck.graalvm-native-image");

        Object extension = project.getExtensions().getByName("nativeImage");
        assertThat(extension, instanceOf(NativeImageExtension.class));
    }

    @Test public void pluginRegistersNativeImageTask() {
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("java");

        project.getPlugins().apply("org.mikeneck.graalvm-native-image");

        Task nativeImageTask = project.getTasks().getByName("nativeImage");
        assertNotNull(nativeImageTask);
        assertThat(nativeImageTask, instanceOf(NativeImageTask.class));
    }
}
