name: version availability test
"on":
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      memo:
        description: memo
        required: false
jobs:
  test:
    name: Gradle-${{ matrix.version }} nativeImage
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 7.3.1
          - "7.2"
          - 7.1.1
          - 7.0.2
          - 6.9.1
          - 6.8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@8bbfe44ef9c6f5c07e5af036a1bffd561c037d18
        with:
          graalvm-version: 20.3.0.java11
      - name: Install GraalVM native image
        run: gu install native-image
      - name: Cache Gradle Wrapper
        id: gradle
        uses: actions/cache@v1
        with:
          path: |-
            ~/.gradle/caches
            ~/.gradle/wrapper
            .cache
          key: wrapper-${{ matrix.version }}
          restore-keys: wrapper-
      - name: Run Test
        run: ./version-tests/test.sh
        env:
          GRADLE_VERSION: ${{ matrix.version }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
